[2024-10-04T08:29:37.403+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-04T08:29:37.456+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: uber_taxi_dag1.run_pipeline scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-10-04T08:29:37.477+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: uber_taxi_dag1.run_pipeline scheduled__2024-10-01T00:00:00+00:00 [queued]>
[2024-10-04T08:29:37.486+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-04T08:29:37.538+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_pipeline> on 2024-10-01 00:00:00+00:00
[2024-10-04T08:29:37.577+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1161) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T08:29:37.616+0000] {standard_task_runner.py:72} INFO - Started process 1168 to run task
[2024-10-04T08:29:37.603+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'uber_taxi_dag1', 'run_pipeline', 'scheduled__2024-10-01T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/taxi_data_pipeline.py', '--cfg-path', '/tmp/tmpqpp5ycmr']
[2024-10-04T08:29:37.628+0000] {standard_task_runner.py:105} INFO - Job 20: Subtask run_pipeline
[2024-10-04T08:29:38.238+0000] {task_command.py:467} INFO - Running <TaskInstance: uber_taxi_dag1.run_pipeline scheduled__2024-10-01T00:00:00+00:00 [running]> on host be9392c3401c
[2024-10-04T08:29:38.607+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='uber_taxi_dag1' AIRFLOW_CTX_TASK_ID='run_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T00:00:00+00:00'
[2024-10-04T08:29:38.612+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-04T08:29:43.559+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/src/data_transformation.py:69 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-10-04T08:29:46.468+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-04T08:29:46.529+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-04T08:29:46.531+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=uber_taxi_dag1, task_id=run_pipeline, run_id=scheduled__2024-10-01T00:00:00+00:00, execution_date=20241001T000000, start_date=20241004T082937, end_date=20241004T082946
[2024-10-04T08:29:46.607+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-04T08:29:46.656+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T08:29:46.658+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
