[2024-10-04T08:20:33.833+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-04T08:20:33.847+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: uber_taxi_dag.run_pipeline manual__2024-10-04T08:15:26.060609+00:00 [queued]>
[2024-10-04T08:20:33.853+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: uber_taxi_dag.run_pipeline manual__2024-10-04T08:15:26.060609+00:00 [queued]>
[2024-10-04T08:20:33.853+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2024-10-04T08:20:33.863+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_pipeline> on 2024-10-04 08:15:26.060609+00:00
[2024-10-04T08:20:33.880+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=942) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-10-04T08:20:33.877+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'uber_taxi_dag', 'run_pipeline', 'manual__2024-10-04T08:15:26.060609+00:00', '--job-id', '17', '--raw', '--subdir', 'DAGS_FOLDER/taxi_data_pipeline.py', '--cfg-path', '/tmp/tmpip10oewm']
[2024-10-04T08:20:33.881+0000] {standard_task_runner.py:72} INFO - Started process 944 to run task
[2024-10-04T08:20:33.881+0000] {standard_task_runner.py:105} INFO - Job 17: Subtask run_pipeline
[2024-10-04T08:20:33.940+0000] {task_command.py:467} INFO - Running <TaskInstance: uber_taxi_dag.run_pipeline manual__2024-10-04T08:15:26.060609+00:00 [running]> on host be9392c3401c
[2024-10-04T08:20:34.017+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='uber_taxi_dag' AIRFLOW_CTX_TASK_ID='run_pipeline' AIRFLOW_CTX_EXECUTION_DATE='2024-10-04T08:15:26.060609+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-04T08:15:26.060609+00:00'
[2024-10-04T08:20:34.019+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-04T08:20:35.271+0000] {logging_mixin.py:190} WARNING - /opt/***/dags/src/data_transformation.py:69 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-10-04T08:20:37.434+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-10-04T08:20:37.480+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-04T08:20:37.481+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=uber_taxi_dag, task_id=run_pipeline, run_id=manual__2024-10-04T08:15:26.060609+00:00, execution_date=20241004T081526, start_date=20241004T082033, end_date=20241004T082037
[2024-10-04T08:20:37.538+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-10-04T08:20:37.566+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-04T08:20:37.570+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
